### ISSUE TITLE
Sprint Grows Grass

### ISSUE THREAD

**Issue by EndDragon438** [KyleBCox/TwerkItMeal#10]
Could you add an options section, either in MC options or somewhere else. It could just be a few commands, but it would be nice to be able to turn off sprinting to grow grass into tall grass. Thanks!

**Comment by EndDragon438** [comment]
Just a whitelist for sprint growth along with the shift one would be great.

**Comment by Elpximso** [comment]
I second this, growing grass when you run is really inconvenient

**Comment by Elpximso** [comment]
Okay blacklisting "minecraft:grass" does work

**Comment by ticticboooom** [comment]
yes the blacklist does work but i also agree that this should be defaulted to blacklisted

imma get to it soon
