### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by angelnc1989** [KyleBCox/TwerkItMeal#2]
Hello,
is the whitelist feature implemented yet? On the curseforge page it says TODO, but there is a config for it.
If it is working, how is the syntax for it?

**Comment by ticticboooom** [comment]
The Whitelist has now been implemented and should be working.

the syntax is as follows:

`["minecraft:cobblestone", "minecraft:cobbllestone"]`

change `minecraft:cobblestone` for the block you want to whitelist
