### ISSUE TITLE
Please restrict Function to twerk at same vertical position

### ISSUE THREAD

**Issue by 4Magma** [KyleBCox/TwerkItMeal#3]
When i jump to a lower [elevator](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator) or try to lower my flight height,  unrequested my surrounding are fertilized.

Could you please add a check for height level and ignore shift if 
height changes too much.

**Comment by ticticboooom** [comment]
it currently works at a 5 block difference in the y axis. to limit it to the players current y height would be too restricted
