### ISSUE TITLE
[1.16.4] Crash in Gaiadimension with TwerkItMeal installed

### ISSUE THREAD

**Issue by remplerus** [KyleBCox/TwerkItMeal#4]
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.16.4
 - Forge: 35.1.13
 - TwerkItMeal: 1.3.4
 - Gaia Dimension: 1.3.0

**Crash Report**
https://gist.github.com/remplerus/194e74f21420a619838b97e5d774ec19

**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:
1. Install Gaia Dimension and TwerkItMeal Mods
2. Crouch like you want to grow anything
3. Crash

**Additional context**
This just happens if TwerkItMeal Mods is installed.
After adding Gaiadimension to blacklist, it didn't crash anymore.

**Comment by remplerus** [comment]
Also made a issue post on gaia dimension: https://github.com/Andromander/Gaia-Dimension/issues/78

**Comment by ticticboooom** [comment]
for record this looks like an issue on my end, will keep this updated if that changes. but imma look at it now

**Comment by ticticboooom** [comment]
although upon further inspection this looks like the  block is defferent to what is being expected, i cant find any issues on my side
