### ISSUE TITLE
TwerkItMeal doesn't grow Ancient Sapling

### ISSUE THREAD

**Issue by Wxrlds** [KyleBCox/TwerkItMeal#7]
TwearkItMeal doesn't apply the Bonemeal effect on the Ancient Sapling from [Natures Aura](https://www.curseforge.com/minecraft/mc-mods/natures-aura) when you crouch. TIM is configured to only work on Saplings which the Ancient Sapling is. Not sure if this is an issue of Natures Aura or TIM so reporting this to both.
Minecraft: 1.16.5
Mod Versions:
-NaturesAura-34.0
-TwerkItMeal-1.3.7

**Comment by TNBlueBear** [comment]
Some saplings need to be in a 2x2 square to grow

**Comment by Wxrlds** [comment]
Is there a reason this was closed? For me it still won't grow.
Also the ancient sapling doesn't need to be in a 2x2 to grow
