### ISSUE TITLE
[Suggestion] Run for Growth Effect?

### ISSUE THREAD

**Issue by Darkosto** [KyleBCox/TwerkItMeal#8]
Hey!

Back in my younger days playing skyblocks, most noteably the greatest skyblock pack that has ever been made SkyFactory 3 (due to downloads) and then the second greatest skyblock pack ever made SkyFactory 4(because it has slightly less downloads), I did **not** twerk because it was against my totally real religion that I have for this story. The anti-miley-montana-ianity. Anyways, the Olsen twins are very different now then they were in my youth. Do you remember Ecto Cooler? It was delicious! I sipped it from my juice box after school every day! 

ANYWAYS, I also ran around my saplings to grow them using Twerking mods. Would you be so kind as to add the option to run in the vicinity of the crops to apply bonemeal effects. I was going say something else but I can't remember. 

Have fun and good luck + take care,
Draksoto

**Comment by ticticboooom** [comment]
will get this added asap

**Comment by ticticboooom** [comment]
implemented this
